public class CurrencyMetadata
{
    public static final Map<String, Metadata> CURRENCY_METADATA = new Map<String, Metadata>
    {
        'ADP' => new Metadata('', 'Andorran Peseta'),
        'AED' => new Metadata('', 'UAE Dirham'),
        'AFA' => new Metadata('', 'Afghanistan Afghani'),
        'ALL' => new Metadata('Lek', 'Albanian Lek'),
        'AMD' => new Metadata('AMD', 'Armenian Dram'),
        'ANG' => new Metadata('ƒ', 'Neth Antilles Guilder'),
        'AOA' => new Metadata('', 'Angola Kwanza'),
        'ARS' => new Metadata('$', 'Argentine Peso'),
        'ATS' => new Metadata('', 'Austrian Schilling'),
        'AUD' => new Metadata('$', 'Australian Dollar'),
        'AWG' => new Metadata('ƒ', 'Aruba Guilder'),
        'AZM' => new Metadata('', 'Azerbaijanian Manat'),
        'BAM' => new Metadata('KM', 'Bosnia and Herzegovina Convertible Marks'),
        'BBD' => new Metadata('$', 'Barbados Dollar'),
        'BDT' => new Metadata('Bt.', 'Bangladesh Taka'),
        'BEF' => new Metadata('', 'Belgian Franc'),
        'BGL' => new Metadata('', 'Lev'),
        'BGN' => new Metadata('', 'Bulgaria Lev'),
        'BHD' => new Metadata('BD', 'Bahraini Dinar'),
        'BIF' => new Metadata('', 'Burundi Franc'),
        'BMD' => new Metadata('$', 'Bermudian Dollar'),
        'BND' => new Metadata('$', 'Brunei Dollar'),
        'BOB' => new Metadata('Bs', 'Bolivian Boliviano'),
        'BOV' => new Metadata('', 'Bolivia Mvdol'),
        'BRL' => new Metadata('R$', 'Brazilian Real'),
        'BSD' => new Metadata('$', 'Bahamian Dollar'),
        'BTN' => new Metadata('', 'Bhutan Ngultrum'),
        'BWP' => new Metadata('P', 'Botswana Pula'),
        'BYB' => new Metadata('', 'Belarussian Ruble'),
        'BYR' => new Metadata('p.', 'Belarussian Ruble'),
        'BZD' => new Metadata('$', 'Belize Dollar'),
        'CAD' => new Metadata('$', 'Canadian Dollar'),
        'CDF' => new Metadata('', 'Franc Congolais'),
        'CHF' => new Metadata('CHF', 'Swiss Franc'),
        'CLF' => new Metadata('', 'Unidades de fomento'),
        'CLP' => new Metadata('$', 'Chilean Peso'),
        'CNY' => new Metadata('', 'Chinese Yuan Renminbi'),
        'COP' => new Metadata('$', 'Colombian Peso'),
        'CRC' => new Metadata('', 'Costa Rica Colon'),
        'CUP' => new Metadata('$', 'Cuban Peso'),
        'CVE' => new Metadata('', 'Cape Verde Escudo'),
        'CYP' => new Metadata('£', 'Cyprus Pound'),
        'CZK' => new Metadata('Kc', 'Czech Koruna'),
        'DEM' => new Metadata('', 'German Mark'),
        'DJF' => new Metadata('', 'Dijibouti Franc'),
        'DKK' => new Metadata('kr', 'Danish Krone'),
        'DOP' => new Metadata('$', 'Dominican Peso'),
        'DZD' => new Metadata('', 'Algerian Dinar'),
        'EEK' => new Metadata('kr', 'Estonian Kroon'),
        'EGP' => new Metadata('£', 'Egyptian Pound'),
        'ERN' => new Metadata('', 'Eritrea Nakfa'),
        'ESP' => new Metadata('', 'Spanish Peseta'),
        'ETB' => new Metadata('', 'Ethiopian Birr'),
        'EUR' => new Metadata('€', 'Euro'),
        'FIM' => new Metadata('', 'Finnish Mark'),
        'FJD' => new Metadata('$', 'Fiji Dollar'),
        'FKP' => new Metadata('£', 'Falkland Islands Pound'),
        'FRF' => new Metadata('', 'French Franc'),
        'GBP' => new Metadata('£', 'Pound Sterling'),
        'GEL' => new Metadata('', 'Georgia Lari'),
        'GHC' => new Metadata('', 'Ghanian Cedi'),
        'GIP' => new Metadata('£', 'Gibraltar Pound'),
        'GMD' => new Metadata('', 'Gambian Dalasi'),
        'GNF' => new Metadata('', 'Guinea Franc'),
        'GRD' => new Metadata('', 'Greek Drachma'),
        'GTQ' => new Metadata('Q', 'Guatemala Quetzal'),
        'GWP' => new Metadata('', 'Guinea-Bissau Peso'),
        'GYD' => new Metadata('$', 'Guyana Dollar'),
        'HKD' => new Metadata('HK$', 'Hong Kong Dollar'),
        'HNL' => new Metadata('L', 'Honduras Lempira'),
        'HRK' => new Metadata('kn', 'Croatian Kuna'),
        'HTG' => new Metadata('', 'Haiti Gourde'),
        'HUF' => new Metadata('Ft', 'Hungarian Forint'),
        'IDR' => new Metadata('Rp', 'Indonesian Rupiah'),
        'IEP' => new Metadata('', 'Irish Punt'),
        'ILS' => new Metadata('', 'New Israeli Shekel'),
        'INR' => new Metadata('Rs', 'Indian Rupee'),
        'IQD' => new Metadata('', 'Iraqi Dinar'),
        'IRR' => new Metadata('Rls', 'Iranian Rial'),
        'ISK' => new Metadata('kr', 'Iceland Krona'),
        'ITL' => new Metadata('', 'Italian Lira'),
        'JMD' => new Metadata('$', 'Jamaican Dollar'),
        'JOD' => new Metadata('JD', 'Jordanian Dinar'),
        'JPY' => new Metadata('', 'Japanese Yen'),
        'KES' => new Metadata('Kshs', 'Kenyan Shilling'),
        'KGS' => new Metadata('', 'Kyrgyzstan Som'),
        'KHR' => new Metadata('', 'Cambodia Riel'),
        'KMF' => new Metadata('', 'Comoro Franc'),
        'KPW' => new Metadata('', 'North Korean Won'),
        'KRW' => new Metadata('W', 'Korean Won'),
        'KWD' => new Metadata('KD', 'Kuwaiti Dinar'),
        'KYD' => new Metadata('$', 'Cayman Islands Dollar'),
        'KZT' => new Metadata('', 'Kazakhstan Tenge'),
        'LAK' => new Metadata('', 'Lao Kip'),
        'LBP' => new Metadata('£', 'Lebanese Pound'),
        'LKR' => new Metadata('Rp', 'Sri Lanka Rupee'),
        'LRD' => new Metadata('$', 'Liberian Dollar'),
        'LSL' => new Metadata('', 'Lesotho Loti'),
        'LTL' => new Metadata('Lt', 'Lithuanian Litas'),
        'LUF' => new Metadata('', 'Luxembourg Franc'),
        'LVL' => new Metadata('Ls', 'Latvian Lats'),
        'LYD' => new Metadata('', 'Libyan Dinar'),
        'MAD' => new Metadata('', 'Moroccan Dirham'),
        'MDL' => new Metadata('', 'Moldovan Leu'),
        'MGF' => new Metadata('', 'Malagasy Franc'),
        'MKD' => new Metadata('MKD', 'Macedonian Denar'),
        'MMK' => new Metadata('', 'Myanmar Kyat'),
        'MNT' => new Metadata('', 'Mongolian Tugrik'),
        'MOP' => new Metadata('', 'Macau Pataca'),
        'MRO' => new Metadata('', 'Mauritania Ouguiya'),
        'MTL' => new Metadata('Lm', 'Maltese Lira'),
        'MUR' => new Metadata('Rs', 'Mauritius Rupee'),
        'MVR' => new Metadata('', 'Maldives Rufiyaa'),
        'MWK' => new Metadata('', 'Malawi Kwacha'),
        'MXN' => new Metadata('$', 'Mexican Peso'),
        'MXV' => new Metadata('', 'Mexican Unidad de Inversion (UDI)'),
        'MYR' => new Metadata('RM', 'Malaysian Ringgit'),
        'MZM' => new Metadata('MT', 'Mozambique Metical'),
        'NAD' => new Metadata('$', 'Namibian Dollar'),
        'NGN' => new Metadata('', 'Nigerian Naira'),
        'NIO' => new Metadata('C$', 'Nicaragua Cordoba Oro'),
        'NLG' => new Metadata('', 'Dutch Guilder'),
        'NOK' => new Metadata('kr', 'Norwegian Krone'),
        'NPR' => new Metadata('Rp', 'Nepalese Rupee'),
        'NZD' => new Metadata('$', 'New Zealand Dollar'),
        'OMR' => new Metadata('RO', 'Rial Omani'),
        'PAB' => new Metadata('B/.', 'Panama Balboa'),
        'PEN' => new Metadata('S/.', 'Peruvian Nuevo Sol'),
        'PGK' => new Metadata('', 'Papua New Guinea Kina'),
        'PHP' => new Metadata('Php', 'Philippine Peso'),
        'PKR' => new Metadata('Rp', 'Pakistan Rupee'),
        'PLN' => new Metadata('zl', 'Polish Zloty'),
        'PTE' => new Metadata('', 'Portuguese Escudo'),
        'PYG' => new Metadata('Gs', 'Paraguayan Guarani'),
        'QAR' => new Metadata('', 'Qatari Rial'),
        'ROL' => new Metadata('lei', 'Romanian Leu'),
        'RON' => new Metadata('lei', 'Romanian New Leu'),
        'RSD' => new Metadata('', 'Serbian Dinar'),
        'RUB' => new Metadata('RUB', 'Russian Rouble'),
        'RUR' => new Metadata('', 'Russian Ruble'),
        'RWF' => new Metadata('', 'Rwanda Franc'),
        'SAR' => new Metadata('SR', 'Saudi Riyal'),
        'SBD' => new Metadata('$', 'Solomon Islands Dollar'),
        'SCR' => new Metadata('Rp', 'Seychelles Rupee'),
        'SDD' => new Metadata('', 'Sudanese Dinar'),
        'SEK' => new Metadata('kr', 'Swedish Krona'),
        'SGD' => new Metadata('$', 'Singapore Dollar'),
        'SHP' => new Metadata('£', 'Saint Helena Pound'),
        'SIT' => new Metadata('SIT', 'Slovenian Tolar'),
        'SKK' => new Metadata('Sk', 'Slovak Koruna'),
        'SLL' => new Metadata('', 'Sierra Leone Leone'),
        'SOS' => new Metadata('S', 'Somali Shilling'),
        'SRG' => new Metadata('', 'Surinam Guilder'),
        'STD' => new Metadata('', 'Sao Tome Dobra'),
        'SVC' => new Metadata('', 'El Salvador Colon'),
        'SYP' => new Metadata('£', 'Syrian Pound'),
        'SZL' => new Metadata('', 'Swaziland Lilageni'),
        'THB' => new Metadata('Bt', 'Thai Baht'),
        'TJR' => new Metadata('', 'Tajik Ruble'),
        'TMM' => new Metadata('', 'Turkmenistan Manat'),
        'TND' => new Metadata('', 'Tunisian Dinar'),
        'TOP' => new Metadata('$', 'Tonga Pa\'anga'),
        'TPE' => new Metadata('', 'Timor Escudo'),
        'TRL' => new Metadata('£', 'Turkish Lira'),
        'TRY' => new Metadata('YTL', 'New Turkish Lira'),
        'TTD' => new Metadata('TT$', 'Trinidad and Tobago Dollar'),
        'TWD' => new Metadata('NT$', 'New Taiwan Dollar'),
        'TZS' => new Metadata('', 'Tanzanian Shilling'),
        'UAH' => new Metadata('', 'Ukraine Hryvnia'),
        'UGX' => new Metadata('', 'Uganda Shilling'),
        'USD' => new Metadata('$', 'U.S. Dollar'),
        'UYU' => new Metadata('$', 'Peso Uruguayo'),
        'UZS' => new Metadata('', 'Uzbekistan Sum'),
        'VEB' => new Metadata('Bs', 'Venezuelan Bolivar'),
        'VEF' => new Metadata('Bs', 'Venezuelan Bolivar Fuerte'),
        'VND' => new Metadata('Dong', 'Vietnam Dong'),
        'VUV' => new Metadata('VT', 'Vanuatu Vatu'),
        'WST' => new Metadata('', 'Samoa Tala'),
        'XAF' => new Metadata('', 'CFA Franc BEAC'),
        'XCD' => new Metadata('$', 'East Caribbean Dollar'),
        'XOF' => new Metadata('', 'CFA Franc BCEAO'),
        'XPF' => new Metadata('', 'Pacific CFP Franc'),
        'YER' => new Metadata('', 'Yemen Riyal'),
        'YUM' => new Metadata('', 'Yugoslav Dinar'),
        'ZAR' => new Metadata('R', 'South African Rand'),
        'ZMK' => new Metadata('', 'Zambian Kwacha'),
        'ZWD' => new Metadata('Z$', 'Zimbabwe Dollar')
    };
    
    public static Metadata getMetadata(String isoCode)
    {
        return CURRENCY_METADATA.get(isoCode);
    }
    
    public static String getSymbol(String isoCode)
    {
        Metadata data = getMetadata(isoCode);
        return data != null ? data.getSymbol() : null;
    }

    public static String getName(String isoCode)
    {
        Metadata data = getMetadata(isoCode);
        return data != null ? data.getName() : null;
    }
    
    public class Metadata
    {
        private String m_symbol;
        private String m_name;
        
        public Metadata(String symbol, String name)
        {
            m_symbol = symbol;
            m_name = name;
        }
        
        public String getSymbol()
        {
            return m_symbol;
        }
        
        public String getName()
        {
            return m_name;
        }
    }
}